apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helpdesk-development

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/environment: development

patches:
  - target:
      kind: Deployment
      name: helpdesk-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: helpdesk-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

commonAnnotations:
  gitops.platform/release-sha: 3bf1dffef919c85a7a74399ea16cacc403ce9f0b

commonAnnotations:
  gitops.platform/release-sha: 299a4010f29a3ffbdd1bb1981a18b07391f0bfda

images:
  - name: ghcr.io/awais-clouddev/gitops-cicd-deployment-platform-api
    newName: ghcr.io/awais-clouddev/gitops-cicd-deployment-platform-api
    digest: sha256:2cb18703782c275034d5da4eb0b20ea5ef3e82679f350ad6356aafff95dea509

  - name: ghcr.io/awais-clouddev/gitops-cicd-deployment-platform-frontend
    newName: ghcr.io/awais-clouddev/gitops-cicd-deployment-platform-frontend
    digest: sha256:07bb490e4a730835a603569b5472005eacdbde0bfb9144fe6ac72b8bed031477
