apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helpdesk-development

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/environment: development

patches:
  - target:
      kind: Deployment
      name: helpdesk-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: helpdesk-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

commonAnnotations:
  gitops.platform/release-sha: 3bf1dffef919c85a7a74399ea16cacc403ce9f0b

commonAnnotations:
  gitops.platform/release-sha: 1e8b9b0c4ba19290715c92ead049b6321d9fbac1

images:
  - name: ghcr.io/awais-clouddev/gitops-cicd-deployment-platform-api
    newName: ghcr.io/awais-clouddev/gitops-cicd-deployment-platform-api
    digest: sha256:6646b1ce8983e8723463d3ab1195e13dc1f47abceda46bd3ea6cb303b7682e99

  - name: ghcr.io/awais-clouddev/gitops-cicd-deployment-platform-frontend
    newName: ghcr.io/awais-clouddev/gitops-cicd-deployment-platform-frontend
    digest: sha256:1a9807fbb95f9845bf63d9c51a2e8b608ed5f29ce921b2f96f5d3bee5df41ecc
