apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: helpdesk-development

resources:
  - ../../base

labels:
  - pairs:
      app.kubernetes.io/environment: development

patches:
  - target:
      kind: Deployment
      name: helpdesk-api
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

  - target:
      kind: Deployment
      name: helpdesk-frontend
    patch: |-
      - op: replace
        path: /spec/replicas
        value: 1

commonAnnotations:
  gitops.platform/release-sha: 3bf1dffef919c85a7a74399ea16cacc403ce9f0b

commonAnnotations:
  gitops.platform/release-sha: 5fa13c4054b87d178571fd935522b466d2eb87d3

images:
  - name: ghcr.io/awais-clouddev/gitops-cicd-deployment-platform-api
    newName: ghcr.io/awais-clouddev/gitops-cicd-deployment-platform-api
    digest: sha256:5548afe344b2ff8706a26d9d4775ce10a7f079ef403c2e365840cae2cc981ee3

  - name: ghcr.io/awais-clouddev/gitops-cicd-deployment-platform-frontend
    newName: ghcr.io/awais-clouddev/gitops-cicd-deployment-platform-frontend
    digest: sha256:b021d5e6a021509e9a279bb026aec6b717c122ca997b0b7b981c4af9f00e6638
